[build]
  # Install frontend deps and build the Vite app
  command = "npm --prefix frontend install && npm --prefix frontend run build"
  # Publish the built static files
  publish = "frontend/dist"

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  # SPA fallback: serve index.html for all client-side routes
  from = "/*"
  to = "/index.html"
  status = 200
